/* Nova Bastion 3D service worker.
 *
 * Offline-first PWA shell. Generated by scripts/build-sw.js; do not edit the
 * PRECACHE list by hand, regenerate it. Version: novabastion-3d-beta12
 *
 * Notes:
 * - cache-first for all same-origin game assets.
 * - navigation requests fall back to the cached index.html when offline.
 * - cross-origin requests are left alone (the game has no runtime CDN deps).
 * - PeerJS cloud signaling is a websocket, not fetch, so nothing to cache.
 */
'use strict';

const CACHE_NAME = "novabastion-3d-beta12";
const INDEX_URL = 'index.html';
const PRECACHE = [
  "assets/models/CREDITS.md",
  "assets/models/aegis_bot.glb",
  "assets/models/colonist.glb",
  "assets/models/command_spire.glb",
  "assets/models/cryo_projector.glb",
  "assets/models/dreadnought.glb",
  "assets/models/engineer.glb",
  "assets/models/fabricator.glb",
  "assets/models/fuel_barrel.glb",
  "assets/models/juggernaut.glb",
  "assets/models/leviathan.glb",
  "assets/models/mortar.glb",
  "assets/models/overmind.glb",
  "assets/models/pulse_turret.glb",
  "assets/models/reactor.glb",
  "assets/models/repair_drone.glb",
  "assets/models/sapper.glb",
  "assets/models/scout_drone.glb",
  "assets/models/siege_walker.glb",
  "assets/models/skitter.glb",
  "assets/models/sniper_nest.glb",
  "assets/models/splitter.glb",
  "assets/models/stasis_pylon.glb",
  "assets/models/supply_crate.glb",
  "assets/models/swarm_mite.glb",
  "assets/models/tesla_coil.glb",
  "assets/models/uplink_dish.glb",
  "assets/models/wall_segment.glb",
  "assets/models/wraith.glb",
  "css/mobile.css",
  "css/refinement.css",
  "css/style.css",
  "icons/icon-128.png",
  "icons/icon-144.png",
  "icons/icon-152.png",
  "icons/icon-192.png",
  "icons/icon-384.png",
  "icons/icon-512.png",
  "icons/icon-72.png",
  "icons/icon-96.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "js/ai.js",
  "js/audio.js",
  "js/cinematic.js",
  "js/config.js",
  "js/debris.js",
  "js/demo3d.js",
  "js/enemies.js",
  "js/events.js",
  "js/game.js",
  "js/gamepad.js",
  "js/ira.js",
  "js/main.js",
  "js/mobile.js",
  "js/models3d.js",
  "js/net.js",
  "js/pbr.js",
  "js/perf.js",
  "js/pick3d.js",
  "js/render3d.js",
  "js/sectors.js",
  "js/sim.js",
  "js/story.js",
  "js/towers.js",
  "js/troops.js",
  "js/ui.js",
  "js/vendor/GLTFLoader.js",
  "js/vendor/fonts/orbitron-var.woff2",
  "js/vendor/fonts/rajdhani-500.woff2",
  "js/vendor/fonts/rajdhani-600.woff2",
  "js/vendor/fonts/rajdhani-700.woff2",
  "js/vendor/peerjs.min.js",
  "js/vendor/post/CopyShader.js",
  "js/vendor/post/EffectComposer.js",
  "js/vendor/post/LuminosityHighPassShader.js",
  "js/vendor/post/MaskPass.js",
  "js/vendor/post/Pass.js",
  "js/vendor/post/RenderPass.js",
  "js/vendor/post/ShaderPass.js",
  "js/vendor/post/UnrealBloomPass.js",
  "js/vendor/three.min.js",
  "manifest.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
      .catch((err) => {
        // A single failed asset must not brick the game page.
        console.error('[NB3D sw] precache failed:', err);
        return self.skipWaiting();
      })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // not ours, ignore

  if (req.mode === 'navigate') {
    // Offline story: the SPA always lands back on the cached title screen.
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((c) => c.put(INDEX_URL, copy)).catch(() => {});
          }
          return res;
        })
        .catch(() => caches.match(INDEX_URL))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE_NAME).then((c) => c.put(req, copy)).catch(() => {});
        }
        return res;
      });
    })
  );
});
