/* Nova Bastion 3D - service worker builder.
 *
 * Reads the game directory and emits sw.js with a versioned precache list
 * of the full app shell. Regenerate after adding/removing asset files:
 *
 *   node scripts/build-sw.js
 *
 * Bump CACHE_VERSION here when the app shell changes so clients upgrade.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CACHE_VERSION = 'novabastion-3d-beta3';

/* Walk the app shell: game code, styles, vendored libs + fonts, icons, manifest.
 * Excluded: dev scripts (build tooling, not game assets), test files, and the
 * store screenshots (listing art, never fetched by the game itself). */
const SHELL_DIRS = ['css', 'js', 'icons', 'assets'];
const EXCLUDE = [
  path.join('js', 'tests'),   // unit tests, not runtime
  'scripts',                  // build tooling
];
const SHELL_FILES = ['index.html', 'manifest.json'];

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = path.relative(ROOT, full);
    if (EXCLUDE.some((e) => rel === e || rel.startsWith(e + path.sep))) continue;
    if (entry.isDirectory()) walk(full, out);
    else if (entry.isFile()) out.push(rel.split(path.sep).join('/'));
  }
}

function main() {
  const files = [...SHELL_FILES];
  for (const d of SHELL_DIRS) walk(path.join(ROOT, d), files);

  // sanity: every precached path must exist on disk
  const missing = files.filter((f) => !fs.existsSync(path.join(ROOT, f)));
  if (missing.length) {
    console.error('missing files in precache list:', missing);
    process.exit(1);
  }
  files.sort();

  const sw = `/* Nova Bastion 3D service worker.
 *
 * Offline-first PWA shell. Generated by scripts/build-sw.js; do not edit the
 * PRECACHE list by hand, regenerate it. Version: ${CACHE_VERSION}
 *
 * Notes:
 * - cache-first for all same-origin game assets.
 * - navigation requests fall back to the cached index.html when offline.
 * - cross-origin requests are left alone (the game has no runtime CDN deps).
 * - PeerJS cloud signaling is a websocket, not fetch, so nothing to cache.
 */
'use strict';

const CACHE_NAME = ${JSON.stringify(CACHE_VERSION)};
const INDEX_URL = 'index.html';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
      .catch((err) => {
        // A single failed asset must not brick the game page.
        console.error('[NB3D sw] precache failed:', err);
        return self.skipWaiting();
      })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // not ours, ignore

  if (req.mode === 'navigate') {
    // Offline story: the SPA always lands back on the cached title screen.
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((c) => c.put(INDEX_URL, copy)).catch(() => {});
          }
          return res;
        })
        .catch(() => caches.match(INDEX_URL))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE_NAME).then((c) => c.put(req, copy)).catch(() => {});
        }
        return res;
      });
    })
  );
});
`;

  const outPath = path.join(ROOT, 'sw.js');
  fs.writeFileSync(outPath, sw);
  console.log('wrote sw.js with', files.length, 'precached files');
}

if (require.main === module) main();
